<template>
  <div class="prose prose-invert">
    <h1>AutoStories</h1>
    <p>AutoStories are autogenerated stories from components in your <code>/components</code> directory!</p>
    <p>
      Theses stories may require playing more with the <code>props</code> and <code>slots</code> controls to get what
      you are after, but they should provide a nice base for you to quickly view and experiment with your components in
      isolation.
    </p>
    <p>
      If you find yourself in the auto generated stories frequently, you may consider creating tailored stories for your
      components!
    </p>
  </div>
</template>
